name: CoreQL

on:
  push:
    branches: [ master, ch-dev/** ]
  pull_request:
    branches: [ master, ch-dev/** ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '10', '12', '14' ]
    name: Node v${{ matrix.node }} Validation

    steps:
    - name: CoreQL Checkout Files
      uses: actions/checkout@v2
    - name: CoreQL Initialize Runtime
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node }}
    - name: CoreQL Initialize Project
      run: rm .yarnrc.yml && yarn set version berry && yarn install
    - name: CoreQL Analysis and Testing
      run: yarn project:build
      timeout-minutes: 3
