name: Code Functionality

on:
  push:
    branches: [ master, ch-dev/** ]
  pull_request:
    branches: [ master, ch-dev/** ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [ '10', '12', '14' ]
    name: Node.js v${{ matrix.node }} Analysis

    steps:
    - name: Checkout Latest Files
      uses: actions/checkout@v2
    - name: Initialize Node.js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node }}
    - name: Initialize Project
      run: rm .yarnrc.yml && yarn set version berry && yarn install
    - name: Analyze Project
      run: yarn project:build
