name: yarn-tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node: [ '8', '10', '12', '14' ]

    name: Node v${{ matrix.node }} Validation

    steps:
    - uses: actions/checkout@v2

    - name: Initialization Node.js Environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node }}

    - name: Install Yarn Dependencies
      run: yarn install && yarn up '*'

    - name: Run Package Tests
      run: yarn project:build
      timeout-minutes: 3
