name: SnykQL

on:
  push:
    branches: [ master, ch-dev/** ]
  pull_request:
    branches: [ master, ch-dev/** ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Analyze Project with Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
