name: Code Stability

on:
  push:
    branches: [ master, ch-dev/** ]
  pull_request:
    branches: [ master, ch-dev/** ]
  schedule:
    - cron: '0 13 * * 5'

jobs:
  analysis:
    runs-on: ubuntu-latest
    name: SonarCloud Code Analysis

    steps:
    - name: Checkout Latest Files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Analyze Project
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
